### ISSUE TITLE
XSLT_Output: Save files with extension CSV

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#155] opened 2021-11-24 15:24 UTC
I try to create CSV files with file extension CSV ("my_data.csv"), but it always jumps to "my_data.txt".

What to do?

**Comment by lovettchris** [comment] 2021-11-24 19:11
Ah, so I assume you are trying to provide this my_data.csv name in the XSLT Output text box?  The problem is in the version of XSLT support by .NET frameworks the `<xsl:output method` has only these values: method="xml|html|text" and this determines the output file types (.xml, .html, .txt).

**Comment by lovettchris** [comment] 2021-11-24 19:35
And when I fix this it has perhaps an unintended side effect, you get this from the WebView2 component:

![image](https://user-images.githubusercontent.com/18707114/143302618-61c171ca-6b25-4abd-9fb7-d0b21b675f38.png)

is that what you want?

**Comment by lovettchris** [comment] 2021-11-24 20:08
Fixed here if you want to try out building this version and playing with it:
https://github.com/microsoft/XmlNotepad/pull/156

**Comment by lovettchris** [comment] 2021-11-25 00:53
You can now try it here: https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.48

**Comment by Pierre-de-la-Verre** [comment] 2021-11-25 10:35
For me on Office 2016 and Firefox the same effect
- I defined "my_data.csv" as output
- Press transform
- In the background the file is created, but in foreground a dialogue asks me "Do you want to open or to download it?"
- I click "download"
- it open again a "save as - dialogue", but not in my project folder - just in my download folder.

So we have to think about it - more side effects than improvements?
(it's a luxury problem - renaming an output-file is not that bad .)

**Comment by lovettchris** [comment] 2021-11-26 00:11
Right, ok, let's ponder this for a bit and open a new issue if we come up with a better solution.

**Comment by lovettchris** [comment] 2021-11-27 22:22
Closing for now, we'll see how it goes.

**Closed by lovettchris** 2021-11-27 22:22 UTC
