### ISSUE TITLE
XSL output file is deleted after closing XML Notepad

### ISSUE THREAD

**Issue by moebelwagen** [microsoft/XmlNotepad#130] opened 2021-09-01 09:14 UTC
After performing an XSL transformation and closing XML Notepad the XSL output file is being deleted. It doesn't matter if the filename was specified or not.

This happens after the update from 2.8.0.36 to 2.8.0.43.

If I don't specify the filename, the first specified filename after the update is used. This happens for different input files and persists even after restarting XML Notepad. Not sure if these are two different issues - if so, I will split the report.

**Comment by JamesO2x** [comment] 2021-09-01 15:57
I was going to make this this issue report. I am new to XML Notepad and have only used version 2.8.0.43. I wasn't aware this didn't happen in earlier versions.

I can confirm that this deletion happens for me as well. To confirm what's happening: the HTML file that is output from an XSL Transformation gets deleted when you close XML Notepad. The HTML file even gets deleted when you just change tabs from "Tree View" to "XSL Output" tab. The HTML only seems to exist so long as the XSL Output tab is active.

I recorded a GIF screen capture to show what's happening. This is a Windows folder right next to the XML Notepad window, using the provided Hamlet sample file. You can see the file count changing from 10 to 9, and back again, every time I switch tabs.

https://imgur.com/wDXEudP

The only way I've found to prevent the deletion is to go into the explorer window after the file is created, and manually rename it.

**Comment by lovettchris** [comment] 2021-09-01 20:01
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.44

**Comment by moebelwagen** [comment] 2021-09-02 09:04
Works like a charm, thanks.
Now a `DefaultXsltOutput.htm` is created after I switch to the XSL Output tab. For me it seems too early since I didn't provide a xslt file location (in the XML or via text box) at that point and maybe don't need the htm anyway because I transform to xml. But that's a design question.

I got confused with the output file name because I named it `<my_xslt_name>_output.xml` - and that is exactly the default name if no output name is provided. So forget about the second half of the issue.

**Comment by lovettchris** [comment] 2021-09-02 21:15
Yep I have a bit of a conundrum on the first time you click the tab, on the one hand I want the transform result to be quick, and visible without having to click Transform, on the other hand that requires generating a file to get best performance from the WebView2 component, and so where do I put that file?  Some XSLT output contains references to images in the same folder as the .xml file so that is the best place to put it.  But if the use didn't enter a filename should I keep the file?  That's why I was deleting the file previously :-) But as you pointed out earlier, it's also convenient to keep the file.  Perhaps someone even wants this defaultxsltoutput file so they can cut and paste the html and put it in their blog or something... hence the conundrum.  Let me go with this for a while and see if anyone else complains :-)

**Comment by JamesO2x** [comment] 2021-09-03 17:30
> That's why I was deleting the file previously :-) But as you pointed out earlier, it's also convenient to keep the file. Perhaps someone even wants this defaultxsltoutput file so they can cut and paste the html and put it in their blog or something...

Yep, this is exactly what I'm using it for. Being able to just click the Tab and have an HTML file generated super quick is really useful. Especially when I'm tweaking the XSLT file a lot and need to check the changes frequently.

I think the current solution you have is fine. I don't mind a temporary file being created. I just prefer allowing me (the user) to delete it or keep it, as I see fit. For me, 99% of the time I'm gonna just keep the temporary file that's generated.

This question is slightly related to this issue: Is there a way to define the name of the output HTML file within the original XML file? For example, with the XSL file we can add the line `<?xml-stylesheet type="text/xsl" href="willy.xsl"?>` with href defining where the XSL file is. Is there a similar line of code we can add such as `<?xml-output type="text/html" href="Shakespeare.html"?>` -- this would allow us to have a pre-defined output filename before even loading the file into XML Notepad.

I tried looking on Google about an "XML Output tag" but didn't find any info. But since XML is extensible, it could be supported in XML Notepad anyway, even if it's not "standard".

**Comment by lovettchris** [comment] 2021-09-03 20:05
Great question, I was also looking for such a standard but didn't find one.  I could add this as an XmlNotepad feature though independent of any existing standards.  Let's keep this issue open as a reminder to add this.  Does get a bit weird if you edit will.xsl and change it something that outputs xml, but forget to change the xml-output tag to provide an XML filename...

**Comment by JamesO2x** [comment] 2021-09-03 22:49
> Perhaps something like this `<?xml-output default="output/hamlet.* "?>` so you can specify a relative path, and decide the matching file extension. And I call it a "default" because you can still override it in the XSLT output text box.

That makes perfect sense to me. Sounds like a solid plan.

**Comment by moebelwagen** [comment] 2021-09-04 12:09
What about `<xsl:result-document href="name.html">`? I admit I never used it, but it sounds like the tag you search for. Ok, it is in the transformation and not in the original xml file, but it is standard.

**Comment by JamesO2x** [comment] 2021-09-05 01:17
> 
> 
> What about `<xsl:result-document href="name.html">`? I admit I never used it, but it sounds like the tag you search for. Ok, it is in the transformation and not in the original xml file, but it is standard.

Oh, actually that makes a lot of sense that the default result file for an XSL transform would be in the XSL file itself! I hadn't thought of that, so I didn't even consider to look there.

Yeah, that probably makes the most sense: The default XSL file for a XML file is stored in the XML file itself, and the default HTML file for an XSL transform is stored in the XSL file itself.

And if that's already a standard/common tag to use for XSL, then I would recommend XML Notepad just use that to read the default "result-document".

**Comment by lovettchris** [comment] 2021-09-06 23:04
Looks to me like result-document is an XSLT 2.0 feature that can be used to output "secondary results".  See https://www.w3.org/TR/xslt-20/#result-trees, specifically see the "Example: Multiple Result Documents".

**Comment by JamesO2x** [comment] 2021-09-07 06:46
Hmmm, yeah I don't really know much about it, all this stuff is new to me. I kinda just use XML for my own purposes, and am not an XML/XSL expert by any means.

If you feel like using the `xsl:result` isn't appropriate for this purpose, then using a custom element like you mentioned before `<?xml-output default="output/hamlet.* "?>` might just be a better idea. If I understand XML correctly, the cool thing about it is that you can just make up any tags you want, so long as they don't violate any of the predefined XML, HTML, or PHP tags.

**Comment by lovettchris** [comment] 2021-09-07 18:20
Yep, the X in XML stands for "extensible", even more so when you use a processing instruction it (the "<?" part) then it doesn't conflict with any XML schema that you are using.  So yes, I think I will stick with doing it in the XML document because many stylesheets are quite generic, like "rss-pretty.xsl" transforms any rss feed.  So let's say I have an RSS feed called "foxnews.xml", I'd rather call the output "foxnews.html" rather than "rss-pretty.html".  The stylesheet doesn't know as much about the subject matter and domain as the XML document does.

**Comment by lovettchris** [comment] 2021-09-07 20:06
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.45

**Comment by moebelwagen** [comment] 2021-09-08 08:26
That was super fast!
@JamesO2x, @lovettchris: my initial issue is solved, feel free to close the ticket.

**Closed** 2021-09-08 19:40 UTC
