### ISSUE TITLE
File - New: Keeps the current file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#380] opened 2024-04-10 09:12 UTC
To reproduce:
- open a file
- do something (or not)
- press "File - new"
- it asks you to save (or not)
- click "no" (or yes)
- "nothing" changes. 
 
In detail, it changed the filename in the background, but the file-content is still the same. Is this intended? Usually, a "new file" is empty (or based on a template), but not the same as before .. ??

**Comment by lovettchris** [comment] 2024-04-15 18:58
Hmmm, sounds like a bug, thanks, the window should reset to a new state with no contents.

**Comment by lovettchris** [comment] 2024-04-15 22:35
Actually I can't reproduce this on 2.9.0.8, can you share a screen recording so I can see exactly what you are doing? Thanks.

**Comment by lovettchris** [comment] 2024-04-19 22:59
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.9

**Closed by lovettchris** 2024-04-19 22:59 UTC
