### ISSUE TITLE
Another error when loading XML file

### ISSUE THREAD

**Issue by wernerflamme** [microsoft/XmlNotepad#221] opened 2022-09-07 15:21 UTC
Hi, 
we have electronic invoices incoming, and since I use XN 2.8.0.61, I get an error popup window with many of those files, and the Tree View is blank. The XSL Output shows the file, though.

![2022-09-07 17_08_11-XML Notepad -](https://user-images.githubusercontent.com/3667884/188913841-d37c69bc-f266-47de-aaca-0774834534d0.png)

![2022-09-07 17_09_20-XML Notepad -](https://user-images.githubusercontent.com/3667884/188913835-7ed675e0-f82b-46f2-912e-f32f65b30c98.png)

![2022-09-07 17_08_51-XML Notepad -](https://user-images.githubusercontent.com/3667884/188913842-90234032-9aaa-46c6-a8c0-496a073bb6ee.png)

How can I get XN to display the Tree View again? XN 2.8.0.46 has no problem doing so.

![2022-09-07 17_12_27-XML Notepad -](https://user-images.githubusercontent.com/3667884/188914618-88fdbbf7-f9f2-49c6-b4e4-a2a62b5d1020.png)

It is the same file in both cases, but 2.8.0.61 shows a false name - the name of the file that was loaded last without errors.

At first I thought that WebView2 might be the reason, but I'm running both packages on the same host, so WebView2 can't be the reason.

Regards,
Werner

**Comment by lovettchris** [comment] 2022-09-07 17:37
Thanks for the bug report, it would be helpful if you could share a minimal version of the XML file that produces this error, if you can't share it here but you can email it to me my address is "clovett" at the company I work at dot com :-) Thanks.

**Comment by lovettchris** [comment] 2022-09-09 01:05
I am able to open this sample XML file containing a digital signature:
[foo.zip](https://github.com/microsoft/XmlNotepad/files/9531527/foo.zip)

![image](https://user-images.githubusercontent.com/18707114/189251048-8da0c280-4456-4865-82c7-67aa3c04d75b.png)

**Comment by lovettchris** [comment] 2022-09-09 01:06
The error message saying "Signature-Element" is not declared, sounds like an XSD Schema validation error, can you also report the contents of the View/Schemas dialog, and try and empty it so it looks like this, then try open the file again:

![image](https://user-images.githubusercontent.com/18707114/189251156-dcc4455d-174d-4e97-aa23-d8d8cae29670.png)

**Comment by wernerflamme** [comment] 2022-09-09 08:57
Hi Chris, thank you for investigating! To make the first thing clear: none of my files are signed digitally. Without looking at the element mentioned in the error popup, I guess that it is mandatory for using the scheme. But I don't know which scheme is using this element. I am SAP admin, and usually not fumbling with problems like this.

Next thing, I mainly get XML invoices following the CII and the UBL standards. Up to now, CII seems to be fine, and only UBL (https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=ubl) invoices cause this popup.

So, I found an old invoice I'll mail to you, and the View->Schemas... window looked like ![2022-09-09 10_17_34-XML Notepad -](https://user-images.githubusercontent.com/3667884/189309399-896c129e-2944-4cdf-a4f3-e5578155be38.png)

I chose File->Clear, and klicked OK. The I opened the invoice. XN took some seconds and showed the error again. When switching to Tree View, I get another error popup: 
![2022-09-09 10_26_38-XML Notepad -](https://user-images.githubusercontent.com/3667884/189310683-f383a7b3-4351-49c3-af45-7e739bb59edd.png)

The error text does not fit into a screenshot, so I paste it here:
```
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.Xml.Schema.XmlSchemaValidationException: Das http://www.w3.org/2000/09/xmldsig#:Signature-Element wurde nicht deklariert.
   bei System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
   bei System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet()
   bei System.Xml.Schema.XmlSchemaValidator.Init()
   bei XmlNotepad.Checker.ValidateContext(XmlCache xcache)
   bei XmlNotepad.XmlCache.ValidateModel(ErrorHandler handler)
   bei XmlNotepad.FormMain.OnModelChanged()
   bei XmlNotepad.FormMain.schemasToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4515.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
XmlNotepad
    Assembly-Version: 2.8.0.61.
    Win32-Version: 2.8.0.61.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/XmlNotepad.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4515.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4536.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4390.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4190.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4536.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
XmlNotepad.Model
    Assembly-Version: 2.8.0.61.
    Win32-Version: 2.8.0.61.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/XmlNotepad.Model.DLL.
----------------------------------------
netstandard
    Assembly-Version: 2.0.0.0.
    Win32-Version: 4.8.4084.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll.
----------------------------------------
Microsoft.XmlNotepad
    Assembly-Version: 2.8.0.61.
    Win32-Version: 2.8.0.61.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/Microsoft.XmlNotepad.DLL.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-Version: 1.0.1210.30.
    Win32-Version: 1.0.1210.30.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/Microsoft.Web.WebView2.WinForms.DLL.
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-Version: 1.0.1210.30.
    Win32-Version: 1.0.1210.30.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/Microsoft.Web.WebView2.Core.DLL.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Data.SqlXml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll.
----------------------------------------
System.Xml.Xsl.CompiledQuery.1
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll.
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Users/wflamme/AppData/Local/Apps/2.0/Q2THQC6D.H1H/8GAM8OHW.BGJ/xmln..tion_d2e0d325f5b08396_0002.0008_8c77c6a6e78dd91c/Microsoft.Win32.Registry.DLL.
----------------------------------------
Microsoft.mshtml
    Assembly-Version: 7.0.3300.0.
    Win32-Version: 7.0.3300.0.
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll.
----------------------------------------
System.xml.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Xml.resources.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.
```

Of course, all schemes are back in that window. And the file is still not shown in Tree View.

Since this only happens with 2.8.0.61, but not with 2.8.0.46, I think the reason is the code used to verify the mentioned schemes. In German we call this Verschlimmbesserung (something made worse while trying to make it better) This checking seems to happen more thorougly in the newer version. I'd like an option to disable or "mellow" this verification.

**Comment by lovettchris** [comment] 2022-09-09 20:54
Wow - impressive debugging!  Thanks for sending me the file, I'm working on a fix now.  I found the problem it is caused by the fact that the `UBL-xmldsig-core-schema-2.1.xsd` schema contains a DTD.  Seems the default behavior of XmlSchemaSet changed and refuses to load them, but I found a work around if I load them myself.

I pushed a fix: https://github.com/microsoft/XmlNotepad/commit/054991b1d08883f0871f15e8cb0658e019dcaccc in case you want to try it out, then I will include this fix in the next release.

**Comment by wernerflamme** [comment] 2022-09-11 12:10
Impressive work, Chris! :) Thank you very much!

I'll try to find a colleague who has the tools (and knowledge) to compile the source code. But since we hardly code for Windows environments, I guess I have to wait for the next release.

**Comment by lovettchris** [comment] 2022-09-12 17:48
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.63

**Comment by wernerflamme** [comment] 2022-09-15 21:45
Thank you very much! None of my colleagues was able to build the tool, so I couldn't test.

**Comment by lovettchris** [comment] 2022-09-15 23:24
Great, hopefully it works for you now and we can close this issue?

**Comment by Pierre-de-la-Verre** [comment] 2022-10-12 09:47
@wernerflamme 
> Great, hopefully it works for you now and we can close this issue?

**Comment by lovettchris** [comment] 2023-05-09 02:11
closing, please reopen if you run into the issue in the new version of XML notepad - version 2.8.0.63 or newer.

**Closed by lovettchris** 2023-05-09 02:11 UTC
