### ISSUE TITLE
Used RAM never set free?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#189] opened 2022-04-11 12:27 UTC
It seems that the used RAM is never set free. I opened (via history list) a file with 0.3 MB - then another with 52 MB - then 0.3 and again .. The RAM usage is always increasing, not going down. Bug or feature?
![grafik](https://user-images.githubusercontent.com/13277944/162738473-01e9befc-0027-4db8-93b6-fe0ce8ed0613.png)

Then I "expanded all" in the 53 MB file (yes, I know . a little bit crazy..). The image shows:
a) it used max. 815MB RAM on my 16GB computer. The CPU is working hard, RAM stays unmodified. Then I created a "new file" - RAM stays high ...
![grafik](https://user-images.githubusercontent.com/13277944/162739161-875b098b-4682-45e8-bf9a-61b384bc6398.png)

**Comment by lovettchris** [comment] 2022-04-26 02:35
I pushed some changes in this commit: https://github.com/microsoft/XmlNotepad/commit/ef97d32447345f90888608e94e55e6a2e6301218
And added an a new menu item labelled "GC.Collect" in the Edit menu.  With this I was able to see memory being released after loading a 96mb file as shown in the trace below:
![image](https://user-images.githubusercontent.com/18707114/165207939-71a99b5c-57e9-4ad9-aa21-49036bb68e11.png)

Notice a few important things here:
1) memory is not released immediately when you click "new document" - it is not released until you use the Edit/GC.Collect function.  .NET is a garbage collected system and it won't give up memory when it sees tons of available RAM.  But the GC.Collect call does force it to release the large memory allocated for the 100mb "big.xml" file.  But it will not return to the initial memory usage of 60mb because .NET itself likes to keep a healthy sized of free memory so the next allocations are super quick.

Anyway, please try out these changes and let me know if you see any improvement in your scenario.  If you still see a problem, please include full repro steps of everything you are doing step by step, thanks.

**Comment by Pierre-de-la-Verre** [comment] 2022-04-26 07:50
_I pushed some changes in this commit: ..._
How to use this? Is there an Exe somewhere?

**Comment by lovettchris** [comment] 2022-04-26 19:16
I published a new binary here: [Xml Notepad 2.8.0.59](https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.59)

**Comment by Pierre-de-la-Verre** [comment] 2022-04-27 08:42
Thanks, Chris
a quick test shows results as expected. 
Open File A: 400 MB
expand all A: 810 MB
open file B: 1000 MB
expand all B: reducing to 400 MB, then up to 800 MB

But as mentioned above - it is a rather rare, "luxury" issue with 50MB files: "Expanding all" uses only 800 MB of RAM, further expanding and collapsing single nodes results in heavy CPU load for some seconds. Not important for me, just a hint. See image
![grafik](https://user-images.githubusercontent.com/13277944/165477720-4c86a4a3-0410-4986-9964-832b84dad5af.png)

**Comment by clovett** [comment] 2022-05-15 19:25
Ok, the memory leak is fixed but it looks like you have a new issue which is a performance issue of very slow expand/collapse on large files.

**Comment by lovettchris** [comment] 2022-09-09 00:56
Closing the memory issue, please open an expand/collapse performance issue if you still feel strongly about that one.

**Closed by lovettchris** 2022-09-09 00:56 UTC

**Comment by Pierre-de-la-Verre** [comment] 2022-10-11 09:00
Do you need more information?
________________________________

**Comment by lovettchris** [comment] 2022-10-11 19:32
No I can reproduce the problem - just need to find time to fix it... in the meantime you could perhaps find a tool that breaks your large XML files into smaller chunks so you can edit them, then stitch them back together when you're done, or something.

**Comment by Pierre-de-la-Verre** [comment] 2022-10-11 20:43
Strange - I didn't made a comment 12 hours ago. It seems that the posting above is delayed for some months .. ???
