### ISSUE TITLE
Setup: used folders on Win 10

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#378] opened 2024-04-10 07:59 UTC
Hi Chris
I found these folders on my PC:

c:\Program Files (x86)\LovettSoftware\XmlNotepad\
c:\Users\myname\AppData\Local\Programs\XmlNotepad\
c:\Users\mynamel\AppData\Local\Microsoft\Xml Notepad\

Not very important, but is the last folder - name with blank, subfolder from Microsoft - the "best of all possible solutions"? Or can it be moved to a "XmlNotepad" folder?

Edit:
There is also a blank in the folder, but not in the filename:
%AppData%\Roaming\Microsoft\Xml Notepad\XmlNotepad.settings

**Comment by lovettchris** [comment] 2024-04-15 19:12
Yeah I can probably remove the space, the problem is then I'd need to migrate your settings over from the old location.  I don't recognize the "c:\Users\myname\AppData\Local\Programs\XmlNotepad" path, I wonder if that's a left over from an old version, what is in that folder?

- click once goes into %LOCALAPPDATA%\Apps\2.0\...
- winget version goes into  C:\Program Files\WindowsApps\...
- some xslt cache files go into %LOCALAPPDATA%\Microsoft\Xml Notepad
- and settings go into the roaming folder by default, %AppData%\Microsoft\Xml Notepad\

**Comment by Pierre-de-la-Verre** [comment] 2024-04-16 06:22
In 

c:\Users\<myname>\AppData\Local\Programs\XmlNotepad

there is

names.txt
stats.cmd
XmlStats.exe

**Comment by lovettchris** [comment] 2024-04-19 22:54
Ah, yes, that one is in "Programs" because I'm installing a program (xmlstats.exe) so it is not just user data.

**Comment by lovettchris** [comment] 2024-10-08 00:13
Won't fix for now, please reopen if you feel strongly about it.

**Closed by lovettchris** 2024-10-08 00:13 UTC
