### ISSUE TITLE
Can't start on Windows 10 21H1 64-bit without reboot

### ISSUE THREAD

**Issue by Anton-V-K** [microsoft/XmlNotepad#183] opened 2022-03-29 15:38 UTC
1) I've downloaded the recent version from https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/XmlNotepadSetup.zip (2.8.0.56), unzipped its content and ran `XmlNotepadSetup.msi` (under administrator account).
2) After installation was completed, I switched to my working account (oridnary user), and tried to start the application.
3) It showed the analytics window where I pressed `Yes`. The window was closed and... the main app windows didn't show up, no process in the task manager, no error message box.
4) Another attempts to start the application also have no effect (go to 3)
5) Reboot the PC and start the app again - it starts fine

If the installer detects that some system files are affected during installation, it should warn the user that a reboot is needed.

OS Version: 10.0.19043 Build 19043 (Microsoft Windows 10 Home N 64-bit)

**Comment by lovettchris** [comment] 2022-03-29 17:29
This is a duplicate of https://github.com/microsoft/XmlNotepad/issues/184 and has been fixed, please down the newer version of https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/XmlNotepadSetup.zip, it should be 4167KB (you may need to clear your browser cache to get it).

**Closed** 2022-09-09 02:04 UTC
