### ISSUE TITLE
Ability to set default settings

### ISSUE THREAD

**Issue by Fishkaras** [microsoft/XmlNotepad#63] opened 2020-10-05 21:44 UTC
Hello
Your program is great, but it really lacks for me the ability to always expand to full screen at opening file, or even remember the previous position and size of the window and the ability to always expand all XML-file tags at startup.

Thank you for attention.

**Comment by lovettchris** [comment] 2020-10-06 01:01
Thanks for your suggestions, the app definitely should remember previous position and window size, can you let me know which installer you are using?  Perhaps the app doesn't have permission to write to %LOCALAPPDATA%\Microsoft\Xml Notepad\XmlNotepad.settings, look for   <WindowBounds>94, 299, 1227, 1045</WindowBounds>.   But auto-full screen and auto-expand all xml tags is not something the app currently supports.  But the app does support Windows Automation so you could write a script to trigger the commands that do these things.

**Comment by Pierre-de-la-Verre** [comment] 2021-04-27 10:25
I just tried with 2.8.0.30, and yes:
- it remembers the size and position
- but it does not remember the "maximized" setting. After closed with a maximized window it starts with the previous "not maximized" size

**Comment by lovettchris** [comment] 2021-04-27 16:51
Correct, it does not remember maximized (or minimized) state.  It only remembers the "restored" size and position.

**Comment by lovettchris** [comment] 2021-06-10 18:56
I'd like to close this "by design" for now.  Remembering maximized state is tricky when it comes to changing monitor resolutions and/or orientations.  Most apps I've used that remember window positions do not remember maximized state.

**Closed by lovettchris** 2021-06-10 18:56 UTC
